apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: klub-ada
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: klub-ada
    newName: rg.fr-par.scw.cloud/djnd/klub-ada
    newTag: '2cf7ec4cd90c47d160353c2202571bdc54e3d32d'