apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: klub-ada
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: klub-ada
    newName: rg.fr-par.scw.cloud/djnd/klub-ada
    newTag: '4c4117e1b652373f3a480b0219b0669017b11b2e'