apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: klub-ada
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: klub-ada
    newName: rg.fr-par.scw.cloud/djnd/klub-ada
    newTag: 'b4313f1962599bfccbefee72aed7dadcc9f4b94a'
